feat(search): add route and controller
ESGI-69/marmiton-ai-boosted pull request #18
Opened 2023-09-29 16:34 UTC by Timdev0

2023-10-03 15:38 UTC, mrpinkcat requested changes

2023-10-03 15:38 UTC, mrpinkcat commented on backend/readme.md
> +            "content": "Bien sûr, je peux vous donner une délicieuse recette de pizza maison. Voici les ingrédients dont vous aurez besoin :\n\n..."
Tu peux juste faire en sorte qui quand on tappe sur search, gpt nous renvois un JSON et du coup nous ne renvoyer que je content de ce que nous envois GPT.

2023-10-03 15:46 UTC, Timdev0 commented on backend/readme.md
> +            "content": "Bien sûr, je peux vous donner une délicieuse recette de pizza maison. Voici les ingrédients dont vous aurez besoin :\n\n..."
aaah okk

2023-10-03 21:07 UTC, SebGrd requested changes

2023-10-03 21:07 UTC, SebGrd commented on backend/src/controllers/recipe.ts
> +      const systemMessage = 'Tu es un chatbot et tu es un chef étoilé au guide michelin et tu as une quinzaine d\'années d\'expérience dans le métier avec plusieurs concours culinaires gagnés à l\'in
- Pas besoin de lui dire que c'est un Chat bot.
- Faute à "Donner"

2023-10-04 07:35 UTC, mrpinkcat approved these changes

2023-10-09 12:08 UTC, SebGrd requested changes
Le query builder que tu as fais servira uniquement aux "requêtes" uniques. En gros il ne sera pas utilisable dans le chat bot. Si c'est pas un problème tu peux Approve ce message sinon faudrait adapter. T'en pense quoi @mrpinkcat ?

2023-10-11 10:29 UTC, SebGrd approved these changes

2023-10-11 10:30 UTC, SebGrd approved these changes

2023-10-11 10:31 UTC, merged