17 create the database search engine
ESGI-69/marmiton-ai-boosted pull request #19
Opened 2023-09-29 17:35 UTC by SebGrd

2023-09-29 17:37 UTC, mrpinkcat commented on backend/src/utils/prismaSearchQueryBuilder.ts
> +    const query = queryParams || {};
La ci passe pas

2023-09-29 17:38 UTC, mrpinkcat requested changes
la ci passe pas

2023-10-01 21:06 UTC, mrpinkcat commented on backend/src/controllers/recipe.ts
> +      const { title, description } = req.query as { title?: string; description?: string; };
```suggestion
      const { title, description } = req.query as { title: string; description: string; };
```

Comme tu viens de check le type au dessus

2023-10-01 21:08 UTC, mrpinkcat commented on backend/src/controllers/recipe.ts
> +      const recipes = await recipeSerice.search({ title: title || '', description: description || '' });
fais passer cette logique dans le service

2023-10-01 21:09 UTC, mrpinkcat commented on backend/src/controllers/recipe.ts
> +      const recipes = await recipeSerice.search({ title: title || '', description: description || '' });
```suggestion
      const recipes = await recipeSerice.search({ title, description, });
```

fais passer cette logique dans le service

2023-10-04 07:37 UTC, mrpinkcat approved these changes

2023-10-04 08:58 UTC, Timdev0 approved these changes

2023-10-05 18:34 UTC, merged